### ISSUE TITLE
/(user-screen-name)/status/(status-id) is broken

### ISSUE THREAD

**Issue by AyaMorisawa** [syuilo/Misskey.old#360]
```
Error: Cannot find module '../../models/post'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/misskey/production/node_modules/misskey/src/web/controllers/post.ls:4:8)
1| // Generated by LiveScript 1.3.1
2| var async, Post, PostFavorite, User;
3| async = require('async');
4+ Post = require('../../models/post');
5| PostFavorite = require('../../models/post-favorite');
6| User = require('../../models/user');
7| module.exports = function(req, res){
8|   return async.series([
    at Module._compile (module.js:460:26)
    at Object.require.extensions..ls (/var/www/misskey/production/node_modules/misskey/node_modules/LiveScript/lib/node.js:36:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by ha-dai** [comment]
URL、post→statusではなく？

**Comment by AyaMorisawa** [comment]
still broken

```
Error: Failed to lookup view "status" in views directory "/var/www/misskey/production/node_modules/misskey/lib/web/main/views/pages"
    at EventEmitter.render (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/response.js:961:7)
    at ServerResponse.res.display (/var/www/misskey/production/node_modules/misskey/lib/web/main/server.js:54:18)
    at module.exports (/var/www/misskey/production/node_modules/misskey/lib/web/main/controllers/post.js:6:16)
    at /var/www/misskey/production/node_modules/misskey/lib/web/main/routes/index.js:107:44
    at Layer.handle [as handle_request] (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/misskey/production/node_modules/misskey/node_modules/express/lib/router/index.js:277:22
    at param (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/router/index.js:349:14)
    at param (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/router/index.js:365:14)
    at paramCallback (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/router/index.js:401:21)
    at /var/www/misskey/production/node_modules/misskey/lib/web/main/routes/index.js:20:18
    at /var/www/misskey/production/node_modules/misskey/node_modules/mongoose/lib/query.js:1174:16
    at /var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/kareem/index.js:109:16
```

**Comment by syuilo** [comment]
Fixed
