### ISSUE TITLE
/i/talks is broken

### ISSUE THREAD

**Issue by AyaMorisawa** [syuilo/Misskey.old#440]
https://misskey.xyz/i/talks

```
TypeError: Cannot read property 'length' of undefined
    at eval (eval at <anonymous> (/var/www/misskey/production/node_modules/misskey/node_modules/jade/lib/index.js:218:8), <anonymous>:71:31)
    at eval (eval at <anonymous> (/var/www/misskey/production/node_modules/misskey/node_modules/jade/lib/index.js:218:8), <anonymous>:98:4)
    at eval (eval at <anonymous> (/var/www/misskey/production/node_modules/misskey/node_modules/jade/lib/index.js:218:8), <anonymous>:141:60)
    at res (/var/www/misskey/production/node_modules/misskey/node_modules/jade/lib/index.js:219:38)
    at Object.exports.renderFile (/var/www/misskey/production/node_modules/misskey/node_modules/jade/lib/index.js:380:38)
    at Object.exports.renderFile (/var/www/misskey/production/node_modules/misskey/node_modules/jade/lib/index.js:370:21)
    at View.exports.__express [as engine] (/var/www/misskey/production/node_modules/misskey/node_modules/jade/lib/index.js:417:11)
    at View.render (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/view.js:126:8)
    at tryRender (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/response.js:961:7)
    at ServerResponse.res.display (/var/www/misskey/production/node_modules/misskey/lib/web/main/server.js:54:18)
    at module.exports (/var/www/misskey/production/node_modules/misskey/lib/web/main/controllers/i-talks.js:6:16)
    at /var/www/misskey/production/node_modules/misskey/lib/web/main/routes/index.js:67:47
    at Layer.handle [as handle_request] (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/misskey/production/node_modules/misskey/node_modules/express/lib/router/route.js:131:13)
```

**Comment by syuilo** [comment]
まもなく実装されます
