### ISSUE TITLE
なにも弄ってないのに急にkey $query must not start with '$'などのエラーが出るようになった

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey.old#661]
```
/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
Error: key $query must not start with '$'
    at Error (native)
    at serializeInto (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:599:38)
    at serialize (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/bson.js:46:27)
    at Query.toBin (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/commands.js:116:25)
    at execInitialQuery (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:227:26)
    at nextFunction (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:541:5)
    at Cursor.next [as _next] (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:629:3)
    at fetchDocs (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:586:10)
    at Cursor.toArray (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:613:3)
    at /var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mquery/lib/collection/node.js:29:12
    at handleCallback (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)
    at Collection.find (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/lib/collection.js:325:44)
    at NativeCollection.(anonymous function) [as find] (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:143:28)
    at NodeCollection.find (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mquery/lib/collection/node.js:26:19)
    at Query.find (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mquery/lib/mquery.js:1629:20)
    at Query._find (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/lib/query.js:1019:26)
```

```
/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
Error: key $and must not start with '$'
    at Error (native)
    at serializeInto (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:599:38)
    at serialize (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/bson.js:46:27)
    at Query.toBin (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/commands.js:116:25)
    at execInitialQuery (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:227:26)
    at nextFunction (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:541:5)
    at Cursor.next [as _next] (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:629:3)
    at fetchDocs (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:586:10)
    at Cursor.toArray (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:613:3)
    at /var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mquery/lib/collection/node.js:29:12
    at handleCallback (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)
    at Collection.find (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mongodb/lib/collection.js:325:44)
    at NativeCollection.(anonymous function) [as find] (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:143:28)
    at NodeCollection.find (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mquery/lib/collection/node.js:26:19)
    at Query.find (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/node_modules/mquery/lib/mquery.js:1629:20)
    at Query._find (/var/www/misskey/production/node_modules/misskey/node_modules/mongoose/lib/query.js:1019:26)
```

**Comment by syuilo** [comment]
https://github.com/Automattic/mongoose/issues/1884

**Comment by syuilo** [comment]
関係あるかは分かりませんがyum updateしたら直ったようです。
しかしパッケージをアップデートしたりとかDBをアップデートしたりとかコード弄ったりとかしてないのになぜ急にこういったエラーが発生するようになったのかは不明のままであるため、また再発する可能性があります。
